id: IC1661767
legacy_id: P001683
ocr_import_info:
  bdrc_scan_id: W1KG13829
  source: bdrc
  ocr_info:
    timestamp: '2020-03-24T18:42:55'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T06:47:24.136127+00:00'
last_modified: 2022-08-31 14:47:36.561519
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG13829
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG13829
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཟབ་མོ་ནང་དོན་གྱི་ཚིག་འགྲེལ།
  author: འཇམ་མགོན་ཀོང་སྤྲུལ་བློ་གྲོས་མཐའ་ཡས།
statistics:
  ocr_word_mean_confidence_index: 0.7212673420616634
  ocr_word_median_confidence_index: 0.8100000023841858
quality: null
bases:
  I1KG16117:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG16117
      total_pages: 468
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG16117.txt
    statistics:
      ocr_word_median_confidence_index: 0.8100000023841858
      ocr_word_mean_confidence_index: 0.7212673420616634
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
